apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "veneer.fullname" . }}-config
  labels:
    {{- include "veneer.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
