apiVersion: v1
kind: Service
metadata:
  name: {{ include "karve.fullname" . }}-metrics-service
  labels:
    {{- include "karve.labels" . | nindent 4 }}
  {{- with .Values.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
    - port: {{ .Values.metricsService.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "karve.selectorLabels" . | nindent 4 }}
