name: Tests

on:
  pull_request: {}

jobs:
  test:
    name: Test
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2

      - name: Clone the code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: go.mod
          cache: true  # Enable Go module caching for faster dependency downloads

      - name: Running Tests
        run: |
          go mod tidy
          make test

      - name: Report coverage
        run: make cover
